### ISSUE TITLE
Query Regarding Baseline

### ISSUE THREAD

**Issue by Viresh-R** [mostafa-saad/deep-activity-rec#1]
Hi Mostafa,
Some queries:
1) For the image classification baseline B1: do you just remove the last layer with 1k neurons and add a new output layer layer with 8 neurons(one for each group activity category) , or do you add any more hidden layer between fc7 and the 8 neuron output layer ? 
2)Also, do you take a center crop 227 \* 227 or do you resize the frames instead of cropping?
Thanks

**Comment by mostafa-saad** [comment]
Hi,

Sorry for late reply...just noticed the issue.

We just made the replacement: 1000 => 8 neurons

Our file is same as caffe one: https://github.com/BVLC/caffe/blob/master/models/bvlc_reference_caffenet/train_val.prototxt

**Comment by Viresh-R** [comment]
Thanks for the reply. I have another query. For each video sequence of 41 frames, the dataset contains the annotations for the 21st frame. Are you guys planning on sharing person bounding boxes and track details across the 41 frames ?
Thanks

**Comment by mostafa-saad** [comment]
I am lazy, and probably won't do that :D . The provided code generates the trackelets used in our paper.

We used dlib tracker. Start from the 21st frame, track little forward and little backward. This is how you can generate the tracklet.

**Comment by Viresh-R** [comment]
:) 
Thanks !!

**Comment by Viresh-R** [comment]
For my experiments, I am implementing some of the baselines from your paper in Torch. Do you use dataset augmentation of any kind(multiple random crops, flipping etc) ?  Without any dataset augmentation, I am getting ~51 % accuracy for the B1-ImageClassification baseline, instead of 66.7 %(Table 5 in journal version).

**Comment by mostafa-saad** [comment]
In terms of caffe, we are ussing following:

  transform_param {
    mirror: true
    crop_size: 227
    mean_file: "<some path>"
  }

I guess this means to use the image and its mirro. There is 227 cropping happens, but I don't remember what that equals in caffe.

Otherwise...it is pure image classification case..just alex network fine tuned.

**Comment by Viresh-R** [comment]
Hi Mostafa,
Regarding train-test split of Collective Activity dataset: In Tian Lan's paper "Beyond Actions: Discriminative Models for Contextual Group Activities", authors say that "We select one fourth of the video clips from each activity category to form the test set, and the rest of the video clips are used for training." 
In your paper, do you use the same train-test split as that in Tian Lan's paper, or a different random split ?  Also, would it be possible to share the train-test split info ?

Thanks
Viresh

**Comment by mostafa-saad** [comment]
See the exact split here #5

**Comment by Viresh-R** [comment]
Great !! Thanks a lot for the quick response.

**Comment by pribadihcr** [comment]
For the collective activity dataset, the prediction/output of group activity is per seq or per frame. 

Thanks
Pribadi

**Comment by mostafa-saad** [comment]
As far as I remember, per a frame. One sequence may have variability per class..please review the CA dataset in its homepage and its annotation file.

**Comment by pribadihcr** [comment]
Actually, I am new in LSTM. In Volleyball dataset, in my understanding, the input for training and testing are sequence of frames that are 20 before and 20 after the target frame. So, how about for the Collective activity dataset. 

Thanks
Pribadi

**Comment by mostafa-saad** [comment]
No, in our volleyball experiments it was something like 5 before and 4 after (total 10). Same for CA dataset. We provided 20 before/after for people who have interest in wider temporal window.

**Comment by pribadihcr** [comment]
Oh I see. So, suppose in the CA dataset, for frame-1 until 5, how to choose 5 frame before, since it is not enough.

**Comment by mostafa-saad** [comment]
I don't remember. I know this won't happen in volleyball. May be if was in CA I did some workaround. I will try to check next Monday.

**Comment by Viresh-R** [comment]
Pribadi,
On the CA dataset page, its mentioned that "Every 10th frame in all video sequences was annotated with image location of person, activity id, and pose direction.", i.e. frame 1 is annotated, then frame 11. In Mostafa's paper, its mentioned they use 9 timesteps for CA dataset. So, you could use frames 7-15 to classify frame 11. However, I am not sure if this is what Mostafa did in the paper.

**Comment by Mrchengheng** [comment]
Hi,Mostafa
I am a new learner.I don't know how and where the dlib tracker work in your comment.Hope you can take the time to answer.Thanks.

**Comment by mostafa-saad** [comment]
@Mrchengheng 
Here is Dlib library: http://dlib.net/

Note, I uploaded recently the actual computed tracklets. See dataset section

**Comment by pribadihcr** [comment]
@Viresh-DL 

Do you have any dump ground truth of collective activity dataset?

Thanks

**Comment by mostafa-saad** [comment]
@Viresh-DL 
No. But dataset is available from its site. In other issue thread, I attached the text files for train/val/test
