### ISSUE TITLE
volley DB issue? Inconsistent batch 

### ISSUE THREAD

**Issue by qdinfish** [mostafa-saad/deep-activity-rec#10]
Hi 

I can run the ./script now. And use the db from following link you provided. But I got fowllowing error.
Maybe there is some wrong in the db, how do I debug the issue? Thanks a lot.

http://vml.cs.sfu.ca/wp-content/uploads/volleyballdataset/volleyball.zip
ERROR. Every 1 batch should have the same value. Inconsistent batch # 992-th
Overall unique labels are: 2. The appeared labels are: 3 6 
exePhase3: ../apps/exePhase3.cpp:265: void feature_extraction_pipeline(int&, char**&) [with Dtype = float]: Assertion `false' failed.
------------------------------------------------------

**Comment by jichaoliu** [comment]
[Uploading z_log_dataset_net2.txt…]()


[Uploading log.zip…]()

**Comment by mostafa-saad** [comment]
Files seems not attached.

**Comment by jichaoliu** [comment]
[z_log_dataset_net2.txt](https://github.com/mostafa-saad/deep-activity-rec/files/915066/z_log_dataset_net2.txt)

**Comment by qdinfish** [comment]
attached the log, thx
[log.zip](https://github.com/mostafa-saad/deep-activity-rec/files/915070/log.zip)

**Comment by mostafa-saad** [comment]
May you attach all the generated logs?

**Comment by qdinfish** [comment]
[z_log_dataset_net2.txt](https://github.com/mostafa-saad/deep-activity-rec/files/923527/z_log_dataset_net2.txt)
[z_trainval-test-log (1).txt](https://github.com/mostafa-saad/deep-activity-rec/files/923528/z_trainval-test-log.1.txt)
[z_trainval-test-window-evaluation-log-prop.txt](https://github.com/mostafa-saad/deep-activity-rec/files/923529/z_trainval-test-window-evaluation-log-prop.txt)

**Comment by qdinfish** [comment]
Hi, invalid label for the volleyball-db you provided?

**Comment by mostafa-saad** [comment]
- These are not all logs. 
- What do you mean with invalid label? More details?

**Comment by qdinfish** [comment]
.hi,you mean all logs from p1 and p4 directory？i have attached the logs in p4，so you need the log in p1,right？
.just guess from the logs you printed

**Comment by mostafa-saad** [comment]
yes, all phases logs.

**Comment by qdinfish** [comment]
[all log.zip](https://github.com/mostafa-saad/deep-activity-rec/files/926782/all.log.zip)

I attached all logs, thanks for your time and effort.

**Comment by mostafa-saad** [comment]
The fuse log shows assertion that never occured for me:

exePhase1_2: src/volleyball-dataset-mgr.cpp:148: std::string MostCV::VolleyballVideoData::GetFramePath(std::string, int): Assertion `boost::filesystem::exists(frame_new_path)' failed.

It means something wrong with the dataset on the harddisk. Weired for me. I assume you did not remove frames or played with the datasert files!

Network 1 log is perfect. Whatever fix you do, don't repeat this (time consuming) phase.
