### ISSUE TITLE
Result with pre-trained Inception-V3

### ISSUE THREAD

**Issue by pribadihcr** [mostafa-saad/deep-activity-rec#11]
Hi @mostafa-saad,

Could you re-run your algorithm using pre-trained Inception-V3. Since, in this paper: https://arxiv.org/abs/1611.09078, they use the Inception-V3 and outperform your algorithm.

Thanks

**Comment by mostafa-saad** [comment]
Hi,
I don't see a value from doing that. Maybe in my further work, I do so.
There are also other factors that one can't say what exactly pushed up the performance.
