### ISSUE TITLE
how can I build new activity dataset ? 

### ISSUE THREAD

**Issue by eulerwang** [mostafa-saad/deep-activity-rec#12]
thanks for your wonderful work and share the code . I am reading your paper and your code . I have a puzzle ,  how to build new activity dataset , for example , a game video activity dataset .  I know  you build the dataset by dlib ,but I cannot find step by step guideline to build a new activity dataset employing the dlib.
can  you  list your dataset building step ?  I appreciate it !  Thank you !

**Comment by mostafa-saad** [comment]
It is a long time since I was structuring the dataset. I would say, try to understand volleyball dataset and do same for yours. This should be the easy part.
