### ISSUE TITLE
Link to dataset does not work

### ISSUE THREAD

**Issue by jharaldson** [mostafa-saad/deep-activity-rec#19]
The **Download Link** does not seem to work.
http://vml.cs.sfu.ca/wp-content/uploads/volleyballdataset/volleyball.zip

**Comment by mostafa-saad** [comment]
I just tried and work with me.

**Comment by jharaldson** [comment]
Sorry, seems my Safari browser failed for some reason, works fine with another browser. Thanks!

**Comment by weiyi1991** [comment]
Hi Mostafa, it seems the link is dead now. The lab page vml.cs.sfu.ca is dead either.

**Comment by mostafa-saad** [comment]
Probably something temporary. May you try in a few days, then inform me?

**Comment by meegoStar** [comment]
Same situation as @weiyi1991 .
