### ISSUE TITLE
Dataset no longer downloadabe

### ISSUE THREAD

**Issue by tempdeltavalue** [mostafa-saad/deep-activity-rec#20]
Does anybody know some alternative links to that dataset ? 
http://vml.cs.sfu.ca/wp-content/uploads/volleyballdataset/volleyball.zip

**Comment by mostafa-saad** [comment]
I am contacting them so that the school fixes this issue. In worst case, I will find some way to upload my local copy

**Comment by tempdeltavalue** [comment]
Thank you a lot! 

This dataset is a real pearl among sports video datasets)

**Comment by mostafa-saad** [comment]
Thanks. I have a local copy and if they did not solve this matter in week or so, I will buy some online storage and upload it. It is around 60G.

**Comment by mostafa-saad** [comment]
@temptitle 
Dataset is now alive :)
