### ISSUE TITLE
people tracks

### ISSUE THREAD

**Issue by psycharo-zz** [mostafa-saad/deep-activity-rec#4]
Hello,
The paper mentioned that the model relies on the visual tracking provided by DLib. Is it maybe possible to have those tracks available within the dataset? That would be very useful.

Thanks!

**Comment by mostafa-saad** [comment]
I am pretty busy. If managed to do that soon, I will do so.

**Comment by mostafa-saad** [comment]
@psycharo 
Hi, You asked for that some time ago. Please see Dataset section in the readme page. See updates 1 and 2. I added tracks. I also added Faster Rcnn Detections.
