### ISSUE TITLE
Splitting training/testing for the collective activity dataset

### ISSUE THREAD

**Issue by pribadihcr** [mostafa-saad/deep-activity-rec#5]
Hi @mostafa-saad,

Is there the code how to split the collective activity dataset into testing/training set?.

Thanks

**Comment by mostafa-saad** [comment]
Hi,

In fact, I asked Hossein Hajimirsadeghi  (Highest score on CA dataset so far as I know) for his exact split files. So no code. You can find the exact split we used. Enjoy.

[two_stage_lstm_test.txt](https://github.com/mostafa-saad/deep-activity-rec/files/548568/two_stage_lstm_test.txt)
[two_stage_lstm_train.txt](https://github.com/mostafa-saad/deep-activity-rec/files/548570/two_stage_lstm_train.txt)
[two_stage_lstm_trainval.txt](https://github.com/mostafa-saad/deep-activity-rec/files/548569/two_stage_lstm_trainval.txt)
[two_stage_lstm_val.txt](https://github.com/mostafa-saad/deep-activity-rec/files/548571/two_stage_lstm_val.txt)
