### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by daodaofr** [mostafa-saad/deep-activity-rec#6]
@mostafa-saad 
I tried to run “script-simple.sh”, and I found Phase1 and Phase 2 is ok, but Phase 3 and Phase report the same error when creating the test network, here is what I got:

E0205 16:20:49.591593  6865 exePhase3.cpp:194] Creating the test network
Segmentation fault (core dumped)
E0205 16:21:00.454159  6886 exePhase4.cpp:169] Creating the test network
Segmentation fault (core dumped)

Do you have any idea? Thank you very much.

Best wishes
Yichao

**Comment by mostafa-saad** [comment]
An issue opened with this problem already.
It is a makefile problem. I am not expert in it. I used to compile from eclipse. I will try to solve soon

https://github.com/mostafa-saad/deep-activity-rec/issues/2

**Comment by hejiaoyu** [comment]
@daodaofr 
Excuse me, I met the same issue. Do you fix that?

**Comment by mostafa-saad** [comment]
@daodaofr @hejiaoyu 

Kindly see issue 2, I listed a workaround
