### ISSUE TITLE
Point out the experiment subject based on in the paper

### ISSUE THREAD

**Issue by pribadihcr** [mostafa-saad/deep-activity-rec#7]
Hi @mostafa-saad 
In the experiment below:
exePhase1_2.cpp 	
exePhase3.cpp 	
exePhase4.cpp 	

Can you point out or indicate which experiment belong to the baseline B, based on the Journal paper?

Thanks.

**Comment by mostafa-saad** [comment]
In fact, only the main model is provided. The execution will not evaluate any baseline.
