### ISSUE TITLE
Query regarding Collective Activity results

### ISSUE THREAD

**Issue by Viresh-R** [mostafa-saad/deep-activity-rec#9]
While testing the single frame baseline models on Collective activity dataset, do you consider only the 10th frame in a sequence ? For some videos, for examples Seq01, annotations are provided for all the frames. While testing, do you consider all the 10 labeled instances in a sequence as separate test cases, or do you discard the first 9 frames ?
Thanks

**Comment by mostafa-saad** [comment]
I only trained/tested with a single frame.

**Comment by Viresh-R** [comment]
Okay. Thanks

**Comment by sinaazar** [comment]
Do you train/test with for example, frames 1, 11, 21, 31, ... in seq1 (or frames 1,2,3,4,5,...)? In annotations file of the seq1 and some other sequences, there are labels and annotations for frames like 2,3,4,5, ... (I think all of them with -1 label for pose).
It will be nice to clarify this to only consider every 10th frame or every labeled frame. I have seen many papers on Collective Activity dataset but no one clarified this issue or released a code that others can infer from it.

**Comment by mostafa-saad** [comment]
I had a 639 test examples, use this number to verify. I think I train/test every 10th frame

**Comment by sinaazar** [comment]
In that case, it is every 10th frame. Including other frames resulted in about 1400 test examples.
Thanks
